"""Add queue (last_posted_at) and feedback (rating)

Revision ID: 166826e49a13
Revises: 819ef54819b2
Create Date: 2025-11-04 22:05:46.404037

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '166826e49a13'
down_revision: Union[str, Sequence[str], None] = '819ef54819b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
