"""Create initial tables: suppliers and users

Revision ID: 176bacd8ef81
Revises: 
Create Date: 2025-10-28 23:54:42.459199

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '176bacd8ef81'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('MYDROP', 'INDEPENDENT', name='supplier_type_enum'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACTIVE', 'BLOCKED', name='supplier_status_enum'), nullable=False),
    sa.Column('owner_pib', sa.String(length=255), nullable=True),
    sa.Column('owner_phone', sa.String(length=20), nullable=True),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('contact_telegram_id', sa.BigInteger(), nullable=True),
    sa.Column('verification_code', sa.String(length=10), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('mydrop_api_key', sa.String(length=255), nullable=True),
    sa.Column('xml_url', sa.Text(), nullable=True),
    sa.Column('website_url', sa.Text(), nullable=True),
    sa.Column('bank_details', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suppliers_contact_telegram_id'), 'suppliers', ['contact_telegram_id'], unique=False)
    op.create_index(op.f('ix_suppliers_name'), 'suppliers', ['name'], unique=False)
    op.create_index(op.f('ix_suppliers_owner_email'), 'suppliers', ['owner_email'], unique=True)
    op.create_index(op.f('ix_suppliers_status'), 'suppliers', ['status'], unique=False)
    op.create_table('users',
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('loyalty_points', sa.Integer(), nullable=False),
    sa.Column('is_registered_customer', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('telegram_id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_suppliers_status'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_owner_email'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_name'), table_name='suppliers')
    op.drop_index(op.f('ix_suppliers_contact_telegram_id'), table_name='suppliers')
    op.drop_table('suppliers')
    # ### end Alembic commands ###
