"""Add Order Spooling (Parent_Child, ItemStatus, drop_price)

Revision ID: 19966116823e
Revises: e3462d72be93
Create Date: 2025-11-07 22:39:37.800843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19966116823e'
down_revision: Union[str, Sequence[str], None] = 'e3462d72be93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
