"""Add PriceRule table for God Mode

Revision ID: 19fa5f8d5a64
Revises: bd4522b5aee1
Create Date: 2025-11-08 20:52:42.258258

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19fa5f8d5a64'
down_revision: Union[str, Sequence[str], None] = 'bd4522b5aee1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
