"""Add Parent-Child Order structure and drop_price

Revision ID: 1e0e669d6ce1
Revises: 6a6a90758fe6
Create Date: 2025-11-07 20:55:06.206532

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e0e669d6ce1'
down_revision: Union[str, Sequence[str], None] = '6a6a90758fe6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
