"""Add ai_in_progress status

Revision ID: 2efd3c812d56
Revises: 5cdfd8dfda50
Create Date: 2025-11-04 23:39:45.681730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2efd3c812d56'
down_revision: Union[str, Sequence[str], None] = '5cdfd8dfda50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
