"""Add Parent-Child Order structure and drop_price

Revision ID: 6a6a90758fe6
Revises: a90e9050cd93
Create Date: 2025-11-07 20:45:59.431041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a6a90758fe6'
down_revision: Union[str, Sequence[str], None] = 'a90e9050cd93'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
