"""Add last_posted_at to Supplier and Product for queue

Revision ID: 6a8be2d9c4d1
Revises: 3b8f807b341b
Create Date: 2025-11-04 21:13:32.672961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a8be2d9c4d1'
down_revision: Union[str, Sequence[str], None] = '3b8f807b341b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
