"""Add queue (last_posted_at) and feedback (rating)

Revision ID: 819ef54819b2
Revises: 6a8be2d9c4d1
Create Date: 2025-11-04 21:51:02.839651

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '819ef54819b2'
down_revision: Union[str, Sequence[str], None] = '6a8be2d9c4d1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
