"""Add Parent-Child Order structure and drop_price

Revision ID: a90e9050cd93
Revises: bf512a4a0918
Create Date: 2025-11-07 20:26:41.444140

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a90e9050cd93'
down_revision: Union[str, Sequence[str], None] = 'bf512a4a0918'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
