"""Add payout fields (iban, token) to Supplier

Revision ID: b378518c64f2
Revises: 2efd3c812d56
Create Date: 2025-11-05 19:41:37.111326

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b378518c64f2'
down_revision: Union[str, Sequence[str], None] = '2efd3c812d56'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
