"""Add Parent-Child Order structure and drop_price

Revision ID: bf512a4a0918
Revises: b378518c64f2
Create Date: 2025-11-07 20:24:51.259415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf512a4a0918'
down_revision: Union[str, Sequence[str], None] = 'b378518c64f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
