"""Add status and cancel_reason to OrderItem

Revision ID: c3888d6c4be3
Revises: 1e0e669d6ce1
Create Date: 2025-11-07 21:13:10.185082

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3888d6c4be3'
down_revision: Union[str, Sequence[str], None] = '1e0e669d6ce1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
