"""Add Order Spooling (Parent/Child) and OrderItem status

Revision ID: e3462d72be93
Revises: a7f398664d74
Create Date: 2025-11-07 22:24:41.248202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e3462d72be93'
down_revision: Union[str, Sequence[str], None] = 'a7f398664d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
